apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-backend
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: backend
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: backend
          image: sbakhtoiarov/wp-backend:v1 # image we pushed
          ports:
            - containerPort: 3000
